FROM python:3.10-slim AS venv

RUN apt-get update &&\
    apt-get install -y --no-install-recommends cmake build-essential gcc

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install azure-servicebus

FROM python:3.10-slim
COPY --from=venv /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

COPY order-consumer.py order-producer.py /app/

CMD exec python -u order-consumer.py