apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-producer
  namespace: order
spec:
  selector:
    matchLabels:
      app: order-producer
  template:
    metadata:
      labels:
        app: order-producer
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: order-app-sa
      containers:
      - name: producer
        image: <container_registry_name>.azurecr.io/order-producer:v1
        envFrom:
          - configMapRef:
              name: service-bus-config
        resources:
          requests:
            cpu: 200m