apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer
  namespace: order
spec:
  selector:
    matchLabels:
      app: order-consumer
  template:
    metadata:
      labels:
        app: order-consumer
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: order-app-sa
      containers:
      - name: consumer
        image: <container_registry_name>.azurecr.io/order-consumer:v1
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: service-bus-config
        resources:
          requests:
            cpu: 200m
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: kubernetes.azure.com/scalesetpriority
                  operator: In
                  values:
                  - spot
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
  namespace: order
spec:
  podIdentity:
    provider: azure-workload
    identityId: <identity_client_id>
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-consumer
  namespace: order
spec:
  scaleTargetRef:
    name: order-consumer
  pollingInterval: 15
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: orders
      messageCount: "50"
      namespace: <service_bus_name>
    authenticationRef:
        name: azure-servicebus-auth 